blog/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls import url
from . import views
from blog.models import Post, Topic
from blog.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView


app_name='blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='all'),

    path('post/create',
        OwnerCreateView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = Post,
            template_name = app_name+"/form.html",
            fields = ['title', 'preview_image', 'text']
         ), name='post_create'),

    path('post/<slug:slug>/',
         OwnerDetailView.as_view(
             model= Post,
             template_name=app_name + "/detail.html"),
         name='post-detail'),

    path('post/<slug:slug>/update',
        OwnerUpdateView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = Post,
            fields = ['title', 'slug', 'preview_image', 'text'],
            template_name = app_name+"/form.html"
        ), name='post_update'),

    path('post/<slug:slug>/delete',
        OwnerDeleteView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = Post,
            template_name = app_name+"/delete.html"
        ), name='post_delete'),



]



urlpatterns += [
    #path('topics/', views.get_topic, name='topic-list'),

    path('<slug:slug>/topic', views.get_posts_by_topic, name='topic-articles'),
    path('<slug:slug>/category', views.get_posts_by_category, name='category-posts'),
    #path('<slug:slug>/tutorial', views.get_tuts_posts, name='tuts-posts'),
    path('<slug:slug>/tutorial', views.TutsListView.as_view(), name='tuts-posts'),
    #path('topics/', views.TopicListView.as_view(), name='topic-list'),


]

blog/models.py
import datetime
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.core.validators import MinLengthValidator
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.sitemaps import ping_google

# Create your models here.
'''
class Ogtype(models.Model):
    name = models.CharField(max_length=30,
    help_text='Select the og:type')
'''

class Category(models.Model):
    """Model representing the Category of the post."""
    name = models.CharField(max_length=100,
                            help_text='Enter the Topic (e.g. Blog, Tutorial, etc)')
    slug = models.SlugField(null=False, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category-posts', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Topic(models.Model):
    """Model representing the topic being discussed."""
    name = models.CharField(max_length=100,
                            help_text='Enter the Topic (e.g. Python, Machine Learning, Algorithms, etc)')
    slug = models.SlugField(null=False, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:topic-articles', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Post(models.Model):
    PUBLISH_CHOICES = (
        ('D', 'Save to Drafts'),
        ('P', 'Publish'),)

    OGTYPE_CHOICES = (
        ('blog', 'blog'),
        ('article', 'article'),
        ('website', 'website'),)

    TWITTERCARD_CHOICES = (
        ('summary', 'summary'),
        ('summary_large_image', 'summary_large_image'),)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be 2 characters or more.")]
    )
    summary = models.TextField(
        null=True, blank=True,
    )
    serial_num = models.FloatField(
        null=True, blank=True,
    )
    #text = models.TextField(validators=[MinLengthValidator(2, "Body must be 2 characters or more.")]
    text = RichTextUploadingField(
            validators=[MinLengthValidator(2, "Body must be 2 characters or more.")],
            external_plugin_resources=[(
                'youtube',
                '/static/ckeditor/plugins/youtube/youtube/',
                'plugin.js',
            )],
    )

    published_date = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    topics = models.ManyToManyField(Topic)
    category = models.ManyToManyField(Category)
    prev_img_url = models.URLField(blank=True, null=True)
    prev_img_alt = models.CharField(max_length=200, blank=True, null=True)

    twittercard = models.CharField(max_length=25, choices=TWITTERCARD_CHOICES,
                           help_text='Select twitter:card', blank=True, null=True)
    status = models.CharField(max_length=1, choices=PUBLISH_CHOICES,
                           help_text='Save to Drafts or Publish?', blank=True, null=True)
    ogtype = models.CharField(max_length=25, choices=OGTYPE_CHOICES,
                           help_text='Select the og:type', blank=True, null=True)
    author_twitterhandle = models.CharField(max_length=50, blank=True, null=True)
    site_twitterhandle = models.CharField(max_length=50, blank=True, null=True)
    keywords = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(null=False, unique=True)

    class Meta:
        ordering = ['id']

    def published(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        super().save(force_insert=False, force_update=False)
        try:
            ping_google()
        except Exception:
            pass

        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
'''
    def save(self, force_insert=False, force_update=False):
        super().save(force_insert, force_update)
        try:
            ping_google()
        except Exception:
            pass
'''

blog/views.py
from django.shortcuts import render
from blog.models import Post, Topic, Category
from django.views import View
from django.contrib.humanize.templatetags.humanize import naturaltime
from blog.utils import dump_queries
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator


class PostListView(View):
    template_name = "blog/list_copy.html"
    #paginate_by = 5

    def get(self, request) :
        strval =  request.GET.get("search", False)
        if strval :
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            post_list = Post.objects.filter(query).select_related().order_by('published_date')#[:10]
        else :
            post_list = Post.objects.filter(status='P').order_by('published_date')#[:10]

        paginator = Paginator(post_list, 5)  # Show 5 posts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        ctx = {'page_obj': page_obj, 'search': strval}
        return render(request, self.template_name, ctx)

class TutsListView(View):
    template_name = "blog/tuts_detail_list.html"

    def get(self, request, slug):
        topic = Topic.objects.get(slug=slug)
        post_list = Post.objects.filter(status='P').filter(
            category__name='Tutorial'
        ).filter(
            topics__slug=slug
        ).order_by(
            'serial_num')

        plist = []
        for p in post_list:
            plist.append(p.title)

        paginator = Paginator(post_list, 1)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        ctx = {'page_obj': page_obj, 'topic': topic, 'plist': plist,}
        return render(request, self.template_name, ctx)


def get_posts_by_topic(request, slug):
    posts = Post.objects.filter(status='P').filter(topics__slug=slug).order_by('published_date')
    topic = Topic.objects.get(slug=slug)
    #topic = get_object_or_404(Topic, slug=slug)

    return render(request, 'blog/topic_articles.html', {
        "posts": posts,
        "topic":topic,
    })


def get_posts_by_category(request, slug):
    cat_posts = Post.objects.filter(status='P').filter(category__slug=slug).order_by('published_date') #filter post based on Category (Blog or Tutorial)
    category = Category.objects.get(slug=slug)
    return render(request, 'blog/category_articles.html', {

        "cat_posts": cat_posts,
        "category": category
    })


'''
class TopicListView(generic.ListView):
    model = Topic
    #template_name ='blog/topic_list.html'
    template_name ='blog/side_bar.html'

    def get_queryset(self):
        return Topic.objects.all()'''

blog/templates/blog/author_articles.html
{% extends "base.html" %}

{% block content %}
    <h4> All Blog Articles Published by {{ author.get_full_name|default:author }}</h4>

    {% if posts %}
    <ul>

      {% for mypost in posts %}
      <li>
        <p><a href="{% url 'post-detail' mypost.pk %}">{{ mypost }}</a> Published on: {{ mypost.published_date }}</p>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no Articles to display.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/category_articles.html
{% extends "base_generic.html" %}

{% block content %}
    <h4> All {{ category }} Posts. </h4>

    {% if cat_posts %}
    <ul class="list-unstyled components">

      {% for post in cat_posts %}
<li>
        <a href="{{ post.get_absolute_url }}">
        <div class="card card-body bg-light">
            <div class="col col-sm order-sm-first col-md">
				<div class="media">
                    {# <!--img class="d-flex mr-3 img-thumbnail align-self-center" src="{% static 'blog/media/uploads/2021/10/28/desert.jpg' %}" alt=" "--> #}
                    <div class="media-body">
                       {# <h5 class="mt-0"><span class="badge badge-danger">NEW</span><span class="badge badge-pill badge-secondary">{{ post.title }}</span></h5> #}
                        <h4 class="mt-0"><span class="badge badge-pill badge-secondary">{{ post.title }}</span></h4>
                        <p class="d-none d-sm-block">
                        {% if post.text|length < 201 %}
                            {{ post.text | safe }}
                        {% else %}
                            {{ post.text|slice:"0:200" | safe }}
                        {% endif %}</p></a>
{% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </li>
    </ul>

    {% else %}
      <p>There are no Posts to display.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Post</h1>

<p>Are you sure you want to delete: {{ post }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" value="Cancel" onclick="window.location.href='{% url 'blog:all' %}';return false;">
</form>
{% endblock %}

blog/templates/blog/detail.html
{% extends "base_detail.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->


{% block content %}
<span style="float: right;">
Last updated: {{ post.updated|date:"D d M Y" }}
<p>By: {{ post.author }} </p>

</span>
<div>
    <h3>{{ post.title }}</h3>
</div>
<p>
{{ post.text | safe }}
</p>
<p>
</p>
<p>
<a href="{% url 'blog:all' %}">All posts</a>
</p>
{% endblock %}

blog/templates/blog/form.html
{% extends "base_bootstrap.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form | crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'blog:all' %}';return false;">
  </form>
</p>
{% endblock %}

blog/templates/blog/list_copy.html
{% extends "base_generic.html" %}



{% block content %}
{% if search %}
<h4>Your search results for "{{ search }}"" </h4>
{% else %}
<h4>All Posts </h4>
{% endif %}
<p>
{% if page_obj %}
<ul class="list-unstyled components">
{% for post in page_obj %}
    <li>
        <a href="{{ post.get_absolute_url }}">
        <div class="card card-body bg-light">
            <div class="col col-sm order-sm-first col-md">
				<div class="media">
                    {# <!--img class="d-flex mr-3 img-thumbnail align-self-center" src="{% static 'blog/media/uploads/2021/10/28/desert.jpg' %}" alt=" "--> #}
                    <div class="media-body">
                        {#<h5 class="mt-0"><span class="badge badge-danger">NEW</span><span class="badge badge-pill badge-secondary">{{ post.title }}</span></h5>#}
                        <h4 class="mt-0"><span class="badge badge-pill badge-secondary">{{ post.title }}</span></h4>
                        <p class="d-none d-sm-block">
                        {% if post.text|length < 201 %}
                            {{ post.text | safe }}
                        {% else %}
                            {{ post.text|slice:"0:200" | safe }}
                        {% endif %}</p></a>
{% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </li>
</ul>
{% else %}
  {% if search %}
    <p>There are no posts for your search "{{ search }}".</p>
    {% else %}
    <p>There are no posts to display.</p>
    {% endif %}
{% endif %}


</p>


<!--Pagination-->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                {# <a href="?page=1">&laquo; <button type="button" class="btn btn-danger">First</button></a> #}
                <a href="?page={{ page_obj.previous_page_number }}"><button type="button" class="btn btn-danger">Previous</button></a>
            {% endif %}

            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"><button type="button" class="btn btn-danger">Next</button></a>
                {# <a href="?page={{ page_obj.paginator.num_pages }}"><button type="button" class="btn btn-danger">Last</button> &raquo;</a> #}
            {% endif %}
        </span>
    </div>

    <!--Pagination End-->
{% endblock %}

blog/templates/blog/navbar_cats.html
<ul class="navbar-nav mr-auto">
    {% if categories %}
    {% for category in categories %}
        <span class="navbar-text"><a href="{% url 'blog:category-posts' category.slug %}">{{ category.name }}</a></span>
    {% endfor %}

    {% else %}
    <p>There are no Tutorials to displays.</p>
    {% endif %} 
</ul>

blog/templates/blog/posts_published_by_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h4> My Articles </h4>

    {% if post_list %}
    <ul>

      {% for mypost in post_list %}
      <li>
        <p><a href="{{ article.get_absolute_url }}">{{ mypost }}</a> Published on: {{ mypost.published_date }}</p>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>You have no Articles to display.</p>
      <p>Start writing your own articles here.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/searchbox.html
                    <div style="float:inline-end">
                        <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
                          <form action="{% url 'blog:all' %}">
                            <input type="text" placeholder="Search.." name="search"
                            {% if search %} value="{{ search }}" {% endif %}
                            >
                            <button type="submit"><i class="fa fa-search"></i></button>
                          <a href="{% url 'blog:all' %}"><i class="fa fa-undo"></i></a>
                          </form>
                      </div>

blog/templates/blog/side_bar2.html
  {% block sidebar %}
<nav id="sidebar">
    <div class="sidebar-header">
        <h4><a href = "#">Tutorials</a></h4>
    </div>
    <ul class="list-unstyled components">

        {% if topics %}
        {% for topic in topics %}
{% comment %}
          <li>
            <a href="{% url 'blog:topic-articles' topic.slug %}">{{ topic.name }} </a>
          </li>
          <span class="navbar-text active"><a class="nav-link" href="{% get_topic_sidebar slug=topic.slug %}">Tutorials</a></span>
{% endcomment %}
          <li>
            <a href="{% url 'blog:tuts-posts' topic.slug %}">{{ topic.name }} </a>
          </li>

        {% endfor %}
        {% else %}
        <p>There are no Tutorials to displays.</p>
        {% endif %}


    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a class="download" href="https://www.linkedin.com/in/rashidbawah/">LinkedIn</a>
        </li>
        <li>
            <a class="download" href="https://www.youtube.com/channel/UCFMwPYpRntd_S6jj4XOLZBA">Youtube Channel</a>
        </li>
    </ul>
</nav>

{% endblock %}

blog/templates/blog/sidebar_tutorial_topic.html
{# load tutorial_sidebar #}



<nav id="sidebar">
    <div class="sidebar-header">

        <h4><a href = "#">{{ topic }}</a></h4>
    </div>

    {% if plist %}
    <ul class="list-unstyled components">
        {% for p in plist %}
          <li>
            <a href="#">{{ p }} </a>
          </li>
        {% endfor %}
        {% else %}
        <p>There are no Tutorials to displays.</p>
        {% endif %}

    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a class="download" href="https://www.linkedin.com/in/rashidbawah/">LinkedIn</a>
        </li>
        <li>
            <a class="download" href="https://www.youtube.com/channel/UCFMwPYpRntd_S6jj4XOLZBA">Youtube Channel</a>
        </li>
    </ul>
</hr>
    <ul class="list-unstyled CTAs">
    </ul>
</nav>

blog/templates/blog/topic_articles.html
{% extends "base_generic.html" %}

{% block content %}
    <h4> All Blog Articles Published on {{ topic }}</h4>

    {% if posts %}
    <ul>

      {% for post in posts %}
      <li>
        <p><a href="{{ post.get_absolute_url }}">{{ post }}</a> Published on: {{ post.published_date }}</p>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no Articles to display.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/topic_list.html
{% extends "base_generic.html" %}

{% block content %}
<h4>Topic List</h4>
          {% if topic_list %}
          <ul>
            {% for topic in topic_list %}
              <li>
                <a href="{#{ topic.get_absolute_url }#} {#% url 'blog:topic-articles' %#}">{{ topic.name }} </a>
              </li>
            {% endfor %}
          </ul>
          {% else %}
            <p>There are no topics to displays.</p>
          {% endif %} 
{% endblock %}

blog/templates/blog/tuts_detail_list.html
{% extends "base_generic.html" %}



{% block sidebar %}
{% include "blog/sidebar_tutorial_topic.html" %}
{% endblock %}

{% block content %}

<h4> Learn {{ topic }} </h4>

<p>
{% if page_obj %}
<ul class="list-unstyled components">
{% for post in page_obj %}
    <li>
        <div class="card card-body bg-light">
            <div class="col col-sm order-sm-first col-md">
				<div class="media">

                    <div class="media-body">

                        <h4 class="mt-0"><span class="badge badge-pill badge-secondary">{{ post.title }}</span></h4>
                        <p class="d-none d-sm-block">
                            {{ post.text | safe }}
                        }</p>
{% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </li>
</ul>
{% else %}
  {% if search %}
    <p>There are no posts for your search "{{ search }}".</p>
    {% else %}
    <p>There are no posts to display.</p>
    {% endif %}
{% endif %}


{% comment %}

        <div style="left:10px">
            {% if post.text|length < 201 %}
                {{ post.text | safe }}
            {% else %}
                {{ post.text|slice:"0:200" | safe }}
                <a href="{{ post.get_absolute_url }}">...</a>
            {% endif %}
        </div>
        <small>
        {% if post.author.username %}
            posted by {{ post.author.username }}
        {% endif %}
        {{ post.natural_updated }}
        </small>
{% endcomment %}


</p>


<!--Pagination-->
    <div class="pagination">
        <p><span class="step-links">
            {% if page_obj.has_previous %}
                {# <a href="?page=1">&laquo; <button type="button" class="btn btn-danger">First</button></a> #}
                <a href="?page={{ page_obj.previous_page_number }}"><button type="button" class="btn btn-danger">Previous</button></a>
            {% endif %}

            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"><button type="button" class="btn btn-danger">Next</button></a>
                {# <a href="?page={{ page_obj.paginator.num_pages }}"><button type="button" class="btn btn-danger">Last</button> &raquo;</a> #}
            {% endif %}
        </span></p>
    </div>

    <!--Pagination End-->
{% endblock %}