blog/urls.py
from django.urls import path, reverse_lazy
from django.conf.urls import url
from . import views
from blog.models import Post, Topic
from blog.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView


app_name='blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='all'),

    path('post/create',
        OwnerCreateView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = Post,
            template_name = app_name+"/form.html",
            fields = ['title', 'preview_image', 'text']
         ), name='post_create'),

    path('post/<slug:slug>/',
         OwnerDetailView.as_view(
             model= Post,
             template_name=app_name + "/detail.html"),
         name='post-detail'),

    path('post/<slug:slug>/update',
        OwnerUpdateView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = Post,
            fields = ['title', 'slug', 'preview_image', 'text'],
            template_name = app_name+"/form.html"
        ), name='post_update'),

    path('post/<slug:slug>/delete',
        OwnerDeleteView.as_view(
            success_url=reverse_lazy(app_name+':all'),
            model = Post,
            template_name = app_name+"/delete.html"
        ), name='post_delete'),



]



urlpatterns += [
    #path('topics/', views.get_topic, name='topic-list'),

    path('<slug:slug>/topic', views.get_posts_by_topic, name='topic-articles'),
    path('<slug:slug>/category', views.get_posts_by_category, name='category-posts'),
    #path('<slug:slug>/tutorial', views.get_tuts_posts, name='tuts-posts'),
    path('<slug:slug>/tutorial', views.TutsListView.as_view(), name='tuts-posts'),
    #path('topics/', views.TopicListView.as_view(), name='topic-list'),


]

templates/base_detail.html
{% extends "base_generic.html" %}

{% block meta %}
{% if post.slug in request.path %}

<title> {{ post.title }} </title>
<meta name="description" content="{{ post.summary }}">
<meta name="keywords" content="{{ post.keywords }}">
<meta name="author" content="Rashid Bawah">

<meta property="og:title" content="{{ post.title }}">
<meta name="description" property="og:description" content="{{ post.summary }}">
<meta property="og:image" content="{{ post.prev_img_url }}">
<meta property="og:image:alt" content="{{ post.prev_img_alt }}">
<meta property="og:type" content="{{ post.ogtype }}">

<meta name=”twitter:card” content="{{ post.twittercard }}">
<meta name=”twitter:creator” content="{{ post.author_twitterhandle }}">
<meta name=”twitter:site” content="{{ post.site_twitterhandle }}">

{% else %}
{{ block.super }}
{% endif %}
{% endblock meta %}

templates/base_generic.html
{% load static %}

{% comment %}
{% load tutorial_sidebar %}
{% get_topic_sidebar topic.slug %}
{% endcomment %}


<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <meta name="description" content="Join me on this journey programming. Learn Python, Java, C++, JavaScript, Data Structures and Algorithms">
        <meta name="keywords" content="Python, Data Structures, Algorithms, JavaScript">
        <meta name="author" content="Rashid Bawah">
            {# include "blog/detail_head.html" #}

    <!-- Bootstrap CSS -->
    <!-- build:css css/main.css -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">

        {# <link rel="stylesheet" type="text/css" href="{% static 'blog/style_sidebar.css' %}"> #}
        <link rel="stylesheet" type="text/css" href="{% static 'blog/styles1.css' %}">

        <!-- Scrollbar Custom CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- highlightjs, to highlight codesnippets -->>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/styles/default.min.css">


{% block meta %}
<title>Code247</title>
<meta name="description" content="Join me on this journey programming. Learn Python, Java, C++, JavaScript, Data Structures and Algorithms">
<meta name="keywords" content="Python, Data Structures, Algorithms, JavaScript">
<meta name="author" content="Rashid Bawah">

<meta property="og:title" content="Code247">
<meta name="description" property="og:description" content="Join me on this journey programming.
    Learn Python, Java, C++, JavaScript, Data Structures and Algorithms">
<meta property="og:image" content="https://www.sketchappsources.com/resources/source-image/python-logo.png">
<meta property="og:image:alt" content="Python Logo">
<meta property="og:type" content="website">

<meta name=”twitter:card” content="summary">
<meta name=”twitter:creator” content="@RashidBawah">
<meta name=”twitter:site” content="@RashidBawah">

{% endblock meta %}
    </head>
    <body>



        <nav class="navbar navbar-dark bg-dark navbar-expand-sm fixed-top py-0">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand mr-auto" href="{% url 'home' %}"><img src="{% static '../media/uploads/2021/10/28/desert.jpg' %}" height="35" width="55"></a>
                <h4 class="nav-item active"><a class="nav-link" href="{% url 'home' %}">Coder247++</a></h4>
                <div class="collapse navbar-collapse" id="Navbar">

                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active"><a class="nav-link" href="{% url 'home' %}"><span class="fa fa-home fa-lg"></span>Home</a></li>
                        <li class="nav-item active"><a class="nav-link" href="{% url 'blog:all' %}">All Posts</a></li>

                        {# categories in navbar #}
                        {% if categories %}
                            {% for category in categories %}
                            <li class="nav-item active"><a class="nav-link" href="{% url 'blog:category-posts' category.slug %}">{{ category.name }}s </a></li>
                            {% endfor %}
                        {% endif %}
                    </ul>



                    {% comment %}
                    <ul class="navbar-nav mr-auto">
                        {% if categories %}
                            {% for category in categories %}
                            <span class="navbar-text active"><a class="nav-link" href="{% url 'blog:category-posts' category.slug %}">{{ category.name }}s </a></span>
                            {% endfor %}
                        {% endif %}

                    </ul>
                    {% endcomment %}

                    {% include "blog/searchbox.html" %}
                </div>
            </div>
        </nav>



    <div class="wrapper">
        {% block sidebar %}
        {% include "blog/side_bar2.html" %}
        {% endblock %}
        <div id="content">

            <div class="row">
                <ol class="col-12 breadcrumb">
                    <button type="button" id="sidebarCollapse" class="btn btn-secondary">
                        <i class="fa fa-angle-double-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <!--li class="breadcrumb-item"><a href="{ url 'home'}">Home</a></li>
                    <li class="breadcrumb-item active">About Us</li-->
                </ol>

            </div>

        {% block content %}




        {% endblock %}
        </div>
    </div>


    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.3.1/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>

	 <!-- jQuery first, then Popper.js, then Bootstrap JS. -->
    <!-- build:js js/main.js -->

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>



    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

{% comment %}
    <footer class="footer">
        <div class="container">
            <div class="row">


                <div class="col-7 col-sm-5">
                    <h5>Reach out to us:</h5>
                    <address>
		              4908 134 Ave NW<br>
		              Edmonton, Alberta<br>
		              Canada<br>
                      <i class="fa fa-phone fa-lg"></i>: +1 587 1234 5678<br>
                      <i class="fa fa-fax fa-lg"></i>: +1 780 8765 4321<br>
                      <i class="fa fa-envelope fa-lg"></i>: <a href="blogs@blogbuilders.ca">blogs@blogbuilders.ca</a>

					</address>
                </div>
                <div class="col-12 col-sm-4 align-self-center">
					<div class="text-left"><h5>Lets Connect:</h5></div>
                    <div class="text-left">
                        <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
                        <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook"></i></a>
                        <a class="btn btn-social-icon btn-linkedin" href="https://www.linkedin.com/in/abdul-rashid-bawah-msc-e-i-t-6111451b2/"><i class="fa fa-linkedin"></i></a>
                        <a class="btn btn-social-icon btn-twitter" href="https://twitter.com/RashidBawah"><i class="fa fa-twitter"></i></a>
                        <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i class="fa fa-youtube"></i></a>
                        <a class="btn btn-social-icon" href="mailto:arbawah1@gmail.com"><i class="fa fa-envelope-o"></i></a>
                    </div>

                </div>
           </div>
           <div class="row justify-content-center">
                <div class="col-auto">
                    <p>© Copyright 2021 Blog Builders Inc.</p>
                </div>
           </div>
        </div>
    </footer>
{% endcomment %}
    </body>

</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base_generic.html' %}



{% block content %}

<h4>Recent Posts </h4>
<ul class="list-unstyled components">
{% for post in posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">
        <div class="card card-body bg-light">
            <div class="col col-sm order-sm-first col-md">
				        <div class="media">

                    <div class="media-body">

                        <h4 class="mt-0"><span class="badge badge-pill badge-secondary">{{ post.title }}</span></h4>
                        <p class="d-none d-sm-block">
                        {% if post.text|length < 201 %}
                            {{ post.text | safe }}
                        {% else %}
                            {{ post.text|slice:"0:200" | safe }}
                        {% endif %}</p></a>
{% endfor %}
                    </div>
                </div>

            </div>
        </div>
    </li>
</ul>

<p>
  <a href="{% url 'blog:all' %}">All posts</a>
  </p>

  <button type="button" class="btn btn-secondary">
    <i class="fa fa-align-justify"></i>
    <span>  <a href="{% url 'blog:all' %}">All blog posts</a></span>
</button>
{% endblock %}